---
# chocomilk vars

# Package Changelog
changelog: 'https://raw.githubusercontent.com/itigoag/chocolatey.version/master/lenovo-thinkpad-usb-c-driver.json'

# Regex for Version
version: "{{ register_changelog.content |
  regex_search('[0-9][0-9][0-9][0-9][0-9].[0-9]+')
  }}"

# Download URL
url: "https://download.lenovo.com/pccbbs/mobiles/thinkpad_thunderbolt-3_dock_and_usb-c_dock_driver_v{{ version | regex_replace('\\.0', '') }}.exe"

searchreplace:
  'tools/chocolateyinstall.ps1':
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: "$urlPackage = '{{ url }}'"
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: "$checksumPackage = '{{ file_hash }}'"

# readme to description
readme:
  start: 5
  end: 8

# deploy
deploy:
  - provider: chocolatey
    repository: 'https://nuget.itigo.tech/upload'
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: chocolatey
    repository: 'https://push.chocolatey.org/'
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: github
    name: 'itigo-bot'
    email: 'chocomilk@itigo.ch'
    url: github.com/itigoag/chocolatey.lenovo-thinkpad-usb-c-driver.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://matters.itigo.tech'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'software-packages'
